# Generated by Django 4.2.3 on 2023-08-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='phone_number',
            field=models.CharField(default='8014008100', max_length=100),
            preserve_default=False,
        ),
    ]
