# Generated by Django 4.2.3 on 2023-08-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_alter_entity_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
