# Generated by Django 4.2.3 on 2023-08-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_alter_entity_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
