# Generated by Django 4.2.3 on 2023-08-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0004_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveries', models.IntegerField(default=0)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_api.entity')),
            ],
        ),
    ]
