# Generated by Django 4.2.3 on 2023-08-04 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0005_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bookmarked', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_api.producer')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_api.volunteer')),
            ],
        ),
    ]
