# Generated by Django 4.2.3 on 2023-08-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0006_producerbookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producerbookmark',
            unique_together={('producer', 'volunteer')},
        ),
    ]
