# Generated by Django 4.2.3 on 2023-08-06 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0007_alter_producerbookmark_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('deliveries', models.IntegerField(default=0)),
                ('usda_certified', models.BooleanField(null=True)),
                ('image_link', models.TextField(blank=True)),
                ('website_link', models.TextField(blank=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_api.entity')),
            ],
        ),
        migrations.CreateModel(
            name='FarmItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('consumable', models.BooleanField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.farm')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_api.foodtype')),
            ],
        ),
    ]
