# Generated by Django 4.2.3 on 2023-08-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0008_farm_farmitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bookmarked', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_api.farm')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_api.volunteer')),
            ],
            options={
                'unique_together': {('farm', 'volunteer')},
            },
        ),
    ]
